package com.wallet.enums.status;

public enum TransactionResponseStatus {
    OK,
    OK_EMPTY_LIST,
    CANCELLED_DATA_BASE_ERROR,
    CANCELLED_BALANCE_EXCEEDED,
    CANCELLED_NEGATIVE_BALANCE,
    CANCELLED_PROFILE_NOT_OWN_WALLET,
    CANCELLED_TRANSACTION_NOT_EXIST,
    CANCELLED_UNKNOWN_SCENARIO
}
